version: "3.9"

services:
  memoWorks:
    env_file:
      - .env
    container_name: backend-memoworks
    image: postgres:18.0
    restart: unless-stopped
    environment:
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - memoWorks_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: ricitosdeoro2001/backend-memoworks:latest
    restart: unless-stopped
    ports:
    - "${PORT}:${PORT}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require"
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      memoWorks:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  memoWorks_data: {}




