version: "3.9"

services:
  memoWorks:
    container_name: backend-memoworks
    env_file:
      - .env
    image: postgres:18.0
    restart: unless-stopped
    environment:
      PG_DATABASE: memoWorks
      PG_USER: admin
      PG_PASSWORD: admin
      PG_ROOT_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - memoWorks_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: ricitosdeoro2001/backend-memoworks:latest
    restart: unless-stopped
    ports:
    - "${PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: "Jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require"
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      memoWorks:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  memoWorks_data: {}




