version: "3.9"

services:
  memoWorks:
    image: mysql:8.0
    container_name: memoworks
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: memoWorks
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - memoWorks_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ricitosdeoro2001/backend-memoworks:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://memoWorks:3306/memoWorks?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      memoWorks:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  memoWorks_data: {}

